python2.4-dbm.patch took from http://bugs.gentoo.org/165268
